
spring:
  # Application Metadata:
  application:
    name: ${PROJECT_NAME}

  # Data source configuration for mySQL :
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  # JPA / Hibernate to configure how objects are mapped to mySQL tables:
  jpa:
    hibernate:
      ddl-auto: update
    # Debugging prints formatted SQL for a given operation.
    show-sql: true
    properties:
      hibernate:
        format_sql: true